// scripts/build-tokens.mjs
// Single source-of-truth: src/styles/tokens/**.json  (DTCG-ish).
//   - primitives/colors.json       palette scales + status colors
//   - semantic/colors.json         semantic tokens (raw HSL triples)
//   - semantic/layout.json         radius, nav-height, hero-pad-top
//   - semantic/typography.json     font-display/sans/body  (raw strings)
//   - themes/<name>.json           per-theme deltas  (overrides)
//   - tokens.index.json            load order + description
//
// Emits three artifacts:
//   src/styles/generated/tokens.css        :root + @theme inline + [data-theme=...]
//   src/styles/generated/tokens.ts         typed TS const  (raw triples)
//   src/styles/generated/tokens.flat.json  flat snapshot for inspection / docs
//
// Triggered by:
//   - prebuild / predev npm scripts
//   - Vite watch-tokens plugin during dev
//   - Manual:  node scripts/build-tokens.mjs
//   - Unit test: src/scripts/build-tokens.test.mjs   (imports _main / _emitCSS)
//
// Zero deps. Node 18+. Pure stdlib. ASCII-only to avoid parser surprises.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', 'src', 'styles', 'tokens');
const OUT  = resolve(HERE, '..', 'src', 'styles', 'generated');
const DEFAULT_THEME = 'indigo';

// ----- low-level helpers -----

const readJSON = (file) => readFile(file, 'utf8').then(JSON.parse);

// Strict flatten: leaves are objects with $value (DTCG-ish) OR strings/numbers.
// Skips $-prefixed metadata keys. Preserves nested keys as dot-paths so that
// palette.indigo.500, status.destructive, etc. are reachable as alias targets.
const flatten = (src, out = {}, prefix = '') => {
  for (const [k, v] of Object.entries(src)) {
    if (k.startsWith('$')) continue;
    const key = prefix ? prefix + '.' + k : k;
    if (v !== null && typeof v === 'object' && !Array.isArray(v) && v.$value === undefined) {
      flatten(v, out, key);
    } else {
      out[key] = v;
    }
  }
  return out;
};

// Resolve {a.b.c} aliases against ctx. Idempotent (loop until no change).
const resolveAliases = (raw, ctx) => {
  if (typeof raw !== 'string') return raw;
  let prev = null, cur = raw;
  while (prev !== cur) {
    prev = cur;
    cur = cur.replace(/\{([a-z0-9._-]+)\}/gi, (m, key) => {
      const v = ctx[key];
      if (v === undefined) {
        console.warn('[build-tokens] unresolved alias: ' + key + ' in "' + raw + '"');
        return m;
      }
      return typeof v === 'string' ? v : JSON.stringify(v);
    });
  }
  return cur;
};

// ----- emitters -----

// Keys that get a Tailwind v4 --color-X: var(--X) alias in @theme inline.
const COLOR_ALIASES = [
  'background','foreground','card','card-foreground','popover','popover-foreground',
  'primary','primary-foreground','secondary','secondary-foreground',
  'muted','muted-foreground','accent','accent-foreground',
  'destructive','destructive-foreground','border','input','ring',
];
const SIDEBAR_ALIASES = [
  'sidebar-background','sidebar-foreground','sidebar-primary','sidebar-primary-foreground',
  'sidebar-accent','sidebar-accent-foreground','sidebar-border','sidebar-ring',
];

const toVarName = (key) => '--' + key;

const emitCSS = ({ flat, themes }) => {
  const lines = [
    '/* Generated by scripts/build-tokens.mjs -- DO NOT EDIT. */',
    '/* Source: src/styles/tokens/**.json  (DTCG-ish). */',
    '',
  ];

  // :root -- all flat semantic colors + layout + shadow + sidebar tokens.
  // (Font tokens go in @theme inline as raw values. Dotted keys like
  //  palette.indigo.500 are primitives -- used as alias targets only --
  //  and must NOT leak into :root as --palette-indigo-500.)
  const rootBlock = [':root {'];
  for (const k of Object.keys(flat).sort()) {
    if (k.startsWith('font-')) continue;
    if (k.includes('.')) continue; // skip primitives (alias-only)
    if (typeof flat[k] !== 'string') continue;
    rootBlock.push('  ' + toVarName(k) + ': ' + flat[k] + ';');
  }
  rootBlock.push('}');

  // @theme inline -- Tailwind v4: color aliases + radius derived + raw font tokens.
  const themeInline = ['@theme inline {'];
  // Color aliases use `hsl(var(--X))` wrap so Tailwind v4 utilities
  // (bg-primary, text-foreground, etc.) and consumers that read the alias
  // directly both get a valid CSS color, even though the underlying CSS vars
  // store raw HSL triples. This is the alpha-placeholder convention.
  for (const t of COLOR_ALIASES) {
    if (flat[t] !== undefined) themeInline.push('  --color-' + t + ': hsl(var(--' + t + '));');
  }
  for (const t of SIDEBAR_ALIASES) {
    if (flat[t] !== undefined) themeInline.push('  --color-' + t + ': hsl(var(--' + t + '));');
  }
  themeInline.push('  --radius-sm: calc(var(--radius) - 8px);');
  themeInline.push('  --radius-md: calc(var(--radius) - 4px);');
  themeInline.push('  --radius-lg: var(--radius);');
  for (const t of ['font-display','font-sans','font-body']) {
    if (flat[t] !== undefined) themeInline.push('  --' + t + ': ' + flat[t] + ';');
  }
  themeInline.push('}');

  // [data-theme="..."] -- non-default themes only. Diff against flat defaults
  // so we ONLY emit keys that actually changed (keeps blocks small + diffable).
  const themeBlocks = Object.entries(themes)
    .filter(([name, t]) => name !== DEFAULT_THEME)
    .map(([name, tFlat]) => {
      const inner = Object.entries(tFlat)
        .filter(([k, v]) => {
          if (k.startsWith('font-')) return false;
          if (k.includes('.')) return false;
          if (typeof v !== 'string') return false;
          return v !== flat[k]; // only emit if theme overrides flat
        })
        .sort(([a],[b]) => a.localeCompare(b))
        .map(([k, v]) => '  ' + toVarName(k) + ': ' + v + ';')
        .join('\n');
      return '[data-theme="' + name + '"] {\n' + inner + '\n}';
    })
    .filter((s) => s.includes('\n  ')); // drop empty blocks

  lines.push(rootBlock.join('\n'), '', themeInline.join('\n'));
  if (themeBlocks.length) lines.push('', themeBlocks.join('\n\n'), '');
  return lines.join('\n');
};

// TS emit: per-key raw triple + per-theme override map. Indices are camelCase
// so consumers don't need to escape kebab-case. The regex matches BOTH
// letter and digit after the dash so tokens like `mesh-1` become valid
// identifiers (`mesh1`) instead of leaking the literal `mesh-1` into TS.
const toCamel = (kebab) => kebab.replace(/-([a-z0-9])/gi, (_, c) => c.toUpperCase());

const emitTS = ({ flat, themes }) => {
  const lines = [
    '// Generated by scripts/build-tokens.mjs -- DO NOT EDIT.',
    '// Source: src/styles/tokens/**.json  (DTCG-ish).',
    '',
    '/** Raw HSL triples + dimension strings, NO hsl() wrapper.',
    ' *  Consumers compose with hsl(var(--token) / <alpha>) for alpha modifiers. */',
    'export const TOKENS_DEFAULT = {',
  ];
  for (const k of Object.keys(flat).sort()) {
    // Skip primitives (palette.indigo.500 etc.) -- those are alias sources
    // already baked into semantic values via the resolver. Including them
    // would emit invalid TS identifiers ('palette.indigo.500' has dots).
    if (k.includes('.')) continue;
    if (typeof flat[k] !== 'string') continue;
    lines.push('  ' + toCamel(k) + ': ' + JSON.stringify(flat[k]) + ',');
  }
  lines.push('} as const;', '', '');
  lines.push('/** Per-theme override maps. Indigo is empty (defaults from TOKENS_DEFAULT). */');
  lines.push('export const TOKENS_THEMES = {');
  for (const [name, tokens] of Object.entries(themes)) {
    lines.push('  ' + JSON.stringify(name) + ': {');
    for (const k of Object.keys(tokens).sort()) {
      if (k.includes('.')) continue;
      if (typeof tokens[k] !== 'string') continue;
      // Skip keys that did not actually change from the flat defaults -- keeps
      // theme maps lean and also avoids serialization of dynamic {} entries.
      if (tokens[k] === flat[k]) continue;
      lines.push('    ' + toCamel(k) + ': ' + JSON.stringify(tokens[k]) + ',');
    }
    lines.push('  },');
  }
  lines.push('} as const;', '');
  return lines.join('\n');
};

const emitFlat = ({ flat, themes }) =>
  JSON.stringify({ default: flat, themes }, null, 2) + '\n';

// ----- main pipeline -----

const loadAllSources = async (sources) => {
  const merged = {};
  for (const rel of sources) {
    const data = await readJSON(resolve(ROOT, rel));
    flatten(data, merged);
  }
  return merged;
};

const main = async () => {
  await mkdir(OUT, { recursive: true });
  const index = await readJSON(resolve(ROOT, 'tokens.index.json'));
  const sources = index.sources ?? [];
  const merged = await loadAllSources(sources);

  // Alias context: primitives (palette.X) + status.
  const ctx = {};
  for (const [k, v] of Object.entries(merged)) {
    if (typeof v === 'string') ctx[k] = v;
    else if (v && typeof v === 'object' && typeof v.$value === 'string') ctx[k] = v.$value;
  }

  // Semantic flat: tokens whose top-level value is a { $value: ... } object.
  const flat = {};
  for (const [k, v] of Object.entries(merged)) {
    if (typeof v === 'object' && v && '$value' in v) {
      flat[k] = resolveAliases(v.$value, ctx);
    }
  }

  // Themes: shallow-clone flat baseline, then apply per-theme overrides.
  const themes = {};
  for (const name of [DEFAULT_THEME, 'catppuccin', 'dracula', 'tokyo-night']) {
    themes[name] = { ...flat };
  }
  for (const srcPath of sources) {
    const m = srcPath.match(/^themes\/(.+)\.json$/);
    if (!m) continue;
    const name = m[1];
    const themeFile = await readJSON(resolve(ROOT, srcPath));
    const overrides = themeFile.overrides ?? {};
    for (const [k, v] of Object.entries(overrides)) {
      const raw = typeof v === 'object' && v && '$value' in v ? v.$value : v;
      if (!themes[name]) themes[name] = { ...flat };
      themes[name][k] = resolveAliases(raw, ctx);
    }
  }

  await writeFile(resolve(OUT, 'tokens.css'),       emitCSS({ flat, themes }), 'utf8');
  await writeFile(resolve(OUT, 'tokens.ts'),        emitTS({ flat, themes }),  'utf8');
  await writeFile(resolve(OUT, 'tokens.flat.json'), emitFlat({ flat, themes }), 'utf8');

  const themeKeys = Object.entries(themes).map(([n, t]) => n + '=' + Object.keys(t).length).join(' ');
  console.log('[build-tokens] OK ' + Object.keys(flat).length + ' tokens; themes: ' + themeKeys);
};

// ----- exports for the unit test -----
export { main as _main, flatten as _flatten, resolveAliases as _resolveAliases, emitCSS as _emitCSS, emitTS as _emitTS };

// ----- entrypoint guard (skip when imported) -----
const isEntry = process.argv[1] && resolve(process.argv[1]) === resolve(HERE, 'build-tokens.mjs');
if (isEntry) {
  main().catch((e) => { console.error('[build-tokens] FAILED:', e); process.exit(1); });
}
